# Generated by Django 5.1.3 on 2024-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('appointment_date', models.DateTimeField()),
                ('is_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
